# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1596d7bf3f3e828d0c19e8235315d6c39017829be363ca06b43d9c0f25c50f47144ced02d853da13a53a412754466eef9e620bbc3bc57e2f9a4068fbb328348d

test:
  secret_key_base: f30b3dad9fc1bd97a9867069815c51e8e44b39b928368d7c3af8b5843848aa4442718303c2b816528f0e21be175a5de1a4b9c1b0560d3afd9904219af316b8d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
